import json
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent

def build():
    ex_file = BASE / "data" / "exercises.json"
    fd_file = BASE / "data" / "foods.json"
    
    with open(ex_file, "r", encoding="utf-8") as f:
        exercises = json.load(f)
    with open(fd_file, "r", encoding="utf-8") as f:
        foods = json.load(f)

    ex_map = {e["id"]: e for e in exercises}
    fd_map = {f["id"]: f for f in foods}

    new_ex = [
        {"id": 48, "name": "Decline Barbell Bench Press", "category": "Chest", "primary_muscles": ["Lower Chest", "Chest"], "secondary_muscles": ["Triceps", "Front Delts"], "equipment": "Barbell", "difficulty": "Intermediate", "environment": "Gym", "goal": "Muscle Gain", "instructions": "Secure legs on decline bench. Unrack barbell over lower chest. Lower bar smoothly to lower pectorals. Press back up to lock out.", "start_pos": "Secured on decline bench, bar over lower chest.", "movement": "Lower to lower sternum.", "end_pos": "Full press extension.", "common_mistakes": "Bar touching too high on chest", "safety_notes": "Always lock your legs into the pads securely.", "default_sets": 3, "default_reps": "8-10", "default_rest": 90},
        {"id": 49, "name": "Incline Push-Up", "category": "Chest", "primary_muscles": ["Lower Chest", "Chest"], "secondary_muscles": ["Triceps", "Core"], "equipment": "Bodyweight", "difficulty": "Beginner", "environment": "Home", "goal": "General Fitness", "instructions": "Place hands on an elevated bench or sturdy platform. Keep body in straight line. Lower chest to edge of platform. Push back up.", "start_pos": "Plank with hands elevated on bench.", "movement": "Lower body towards platform.", "end_pos": "Full arm extension.", "common_mistakes": "Sagging hips", "safety_notes": "Great scalable variation for beginners.", "default_sets": 3, "default_reps": "12-15", "default_rest": 60},
        {"id": 50, "name": "Decline Push-Up", "category": "Chest", "primary_muscles": ["Upper Chest", "Chest"], "secondary_muscles": ["Front Delts", "Triceps", "Core"], "equipment": "Bodyweight", "difficulty": "Intermediate", "environment": "Home", "goal": "Muscle Gain", "instructions": "Place feet on bench or elevated surface and hands on the floor. Lower chest to floor under control. Press back up.", "start_pos": "Feet elevated, hands on floor in plank.", "movement": "Lower chest toward floor.", "end_pos": "Full push-up extension.", "common_mistakes": "Hips sagging", "safety_notes": "Maintain firm core tension.", "default_sets": 3, "default_reps": "10-12", "default_rest": 60},
        {"id": 51, "name": "Cable Crossover", "category": "Chest", "primary_muscles": ["Chest"], "secondary_muscles": ["Front Delts"], "equipment": "Cable Machine", "difficulty": "Intermediate", "environment": "Gym", "goal": "Hypertrophy", "instructions": "Set high pulleys with D-handles. Take a slight forward lunge stance. Bring handles down and together across front of hips. Squeeze chest firmly at peak.", "start_pos": "Standing between cable pulleys, slight forward lean.", "movement": "Sweep arms forward and down in an arc.", "end_pos": "Hands meet in front of pelvis, chest contracted.", "common_mistakes": "Using momentum", "safety_notes": "Maintain constant tension throughout.", "default_sets": 3, "default_reps": "12-15", "default_rest": 60},
        {"id": 52, "name": "Chest Dips", "category": "Chest", "primary_muscles": ["Lower Chest", "Chest"], "secondary_muscles": ["Triceps", "Front Delts"], "equipment": "Pull-up Bar", "difficulty": "Intermediate", "environment": "Gym", "goal": "Strength", "instructions": "Grip parallel bars, lean torso forward 30 degrees. Lower until elbows reach 90 degrees. Push through chest back up.", "start_pos": "Supported on dip bars, leaning forward.", "movement": "Lower torso with forward lean.", "end_pos": "Press back up to lock out.", "common_mistakes": "Staying upright (targets triceps more)", "safety_notes": "Stop at 90-degree elbow bend if you feel shoulder pinch.", "default_sets": 3, "default_reps": "8-12", "default_rest": 90},
        {"id": 53, "name": "Machine Chest Press", "category": "Chest", "primary_muscles": ["Chest"], "secondary_muscles": ["Triceps", "Front Delts"], "equipment": "Machines", "difficulty": "Beginner", "environment": "Gym", "goal": "Muscle Gain", "instructions": "Adjust seat height so handles align with mid-chest. Press handles forward until arms are almost straight. Return slowly.", "start_pos": "Seated back against pad, handles at chest level.", "movement": "Press handles away from chest.", "end_pos": "Full press with soft lockout.", "common_mistakes": "Shoulders rolling forward", "safety_notes": "Keep shoulder blades pinned to the back pad.", "default_sets": 3, "default_reps": "10-12", "default_rest": 60},
        {"id": 54, "name": "Pec Deck Fly", "category": "Chest", "primary_muscles": ["Chest"], "secondary_muscles": ["Front Delts"], "equipment": "Machines", "difficulty": "Beginner", "environment": "Gym", "goal": "Hypertrophy", "instructions": "Sit with back firmly against pad, grasp handles or pads with forearms. Bring arms together in front of chest. Hold contraction 1 sec then return.", "start_pos": "Arms open out to sides on machine pads.", "movement": "Squeeze arms together horizontally.", "end_pos": "Pads touch or meet at midline.", "common_mistakes": "Shrugging shoulders", "safety_notes": "Keep chest high and shoulders depressed.", "default_sets": 3, "default_reps": "12-15", "default_rest": 60},
        {"id": 55, "name": "Dumbbell Floor Press", "category": "Chest", "primary_muscles": ["Chest"], "secondary_muscles": ["Triceps"], "equipment": "Dumbbells", "difficulty": "Beginner", "environment": "Home", "goal": "Strength", "instructions": "Lie on the floor with knees bent, holding dumbbells at chest. Press up until arms are straight. Lower until triceps lightly touch the floor, pause, and press.", "start_pos": "Supine on floor, triceps resting on ground holding dumbbells.", "movement": "Press dumbbells upwards vertically.", "end_pos": "Arms locked over chest.", "common_mistakes": "Bouncing elbows hard on the floor", "safety_notes": "Great shoulder-safe pressing variation.", "default_sets": 3, "default_reps": "10-12", "default_rest": 60},
        {"id": 56, "name": "Barbell Deadlift", "category": "Back", "primary_muscles": ["Lower Back", "Hamstrings", "Glutes", "Back"], "secondary_muscles": ["Lats", "Traps", "Forearms", "Core"], "equipment": "Barbell", "difficulty": "Advanced", "environment": "Gym", "goal": "Strength", "instructions": "Stand with feet hip-width, barbell over midfoot. Hinge down, grip bar just outside shins. Brace core, drive through the floor to stand upright. Lower bar with controlled hip hinge.", "start_pos": "Hinged down at bar, shins touching bar, spine locked flat.", "movement": "Drive hips and knees to lock out vertically.", "end_pos": "Standing erect with glutes squeezed.", "common_mistakes": "Rounding lower spine", "safety_notes": "Brace intra-abdominal pressure firmly before pulling.", "default_sets": 4, "default_reps": "5-6", "default_rest": 120},
        {"id": 57, "name": "Chin-Up", "category": "Back", "primary_muscles": ["Lats", "Biceps", "Back"], "secondary_muscles": ["Forearms", "Core"], "equipment": "Pull-up Bar", "difficulty": "Intermediate", "environment": "Gym", "goal": "Strength", "instructions": "Grip bar underhand shoulder-width. Pull chest up to bar focusing on bicep and lat pull. Lower slowly.", "start_pos": "Hanging with supinated grip.", "movement": "Pull body up to chin over bar.", "end_pos": "Chin clears bar.", "common_mistakes": "Swinging legs", "safety_notes": "Keep shoulders packed.", "default_sets": 3, "default_reps": "8-10", "default_rest": 90},
        {"id": 58, "name": "T-Bar Row", "category": "Back", "primary_muscles": ["Back", "Rhomboids", "Lats"], "secondary_muscles": ["Biceps", "Traps"], "equipment": "Barbell", "difficulty": "Intermediate", "environment": "Gym", "goal": "Muscle Gain", "instructions": "Straddle T-bar platform with hips hinged. Grip handles and pull weight towards chest. Squeeze middle back, lower slowly.", "start_pos": "Hinged over T-bar handles.", "movement": "Pull weight into upper abdomen.", "end_pos": "Shoulder blades squeezed.", "common_mistakes": "Rounding spine", "safety_notes": "Keep knees soft and lower back flat.", "default_sets": 3, "default_reps": "8-10", "default_rest": 75},
        {"id": 59, "name": "Inverted Bodyweight Row", "category": "Back", "primary_muscles": ["Back", "Rhomboids"], "secondary_muscles": ["Biceps", "Core", "Rear Delts"], "equipment": "Smith Machine", "difficulty": "Beginner", "environment": "Gym", "goal": "General Fitness", "instructions": "Position bar in rack at waist height. Lie underneath, grip bar with overhand grip. Pull chest to bar keeping body plank-straight.", "start_pos": "Hanging under bar with heels on floor, body straight.", "movement": "Pull chest to bar.", "end_pos": "Chest contacts bar.", "common_mistakes": "Sagging hips", "safety_notes": "Adjust bar higher to make it easier.", "default_sets": 3, "default_reps": "10-12", "default_rest": 60},
        {"id": 60, "name": "Straight Arm Pulldown", "category": "Back", "primary_muscles": ["Lats", "Back"], "secondary_muscles": ["Core", "Triceps"], "equipment": "Cable Machine", "difficulty": "Beginner", "environment": "Gym", "goal": "Hypertrophy", "instructions": "Stand facing high cable with straight bar or rope. Keeping arms almost straight, sweep bar down to thighs. Squeeze lats at bottom.", "start_pos": "Standing hinged 30 deg, arms extended holding cable bar high.", "movement": "Sweep bar in arc down to thighs.", "end_pos": "Bar at upper thighs, lats contracted.", "common_mistakes": "Bending elbows", "safety_notes": "Lock elbow angle and move only through shoulder joint.", "default_sets": 3, "default_reps": "12-15", "default_rest": 60},
        {"id": 61, "name": "Barbell Shrug", "category": "Back", "primary_muscles": ["Traps", "Back"], "secondary_muscles": ["Forearms"], "equipment": "Barbell", "difficulty": "Beginner", "environment": "Gym", "goal": "Strength", "instructions": "Hold barbell in front of thighs with shoulder-width grip. Elevate shoulders straight up towards ears. Hold 1 sec, lower smoothly.", "start_pos": "Standing tall holding barbell at arms length.", "movement": "Shrug shoulders vertically.", "end_pos": "Traps fully contracted at top.", "common_mistakes": "Rolling shoulders", "safety_notes": "Move straight up and down, do not roll.", "default_sets": 3, "default_reps": "12-15", "default_rest": 60},
        {"id": 62, "name": "Hyperextensions", "category": "Back", "primary_muscles": ["Lower Back", "Back"], "secondary_muscles": ["Glutes", "Hamstrings"], "equipment": "Bench", "difficulty": "Beginner", "environment": "Gym", "goal": "Endurance", "instructions": "Lock legs into 45-degree hyperextension bench. Cross arms over chest, hinge down at hips. Raise torso until aligned with legs.", "start_pos": "Hips resting against pad, torso hinged down.", "movement": "Extend spine and hips upward.", "end_pos": "Body forms a straight line.", "common_mistakes": "Hyperextending spine backward at top", "safety_notes": "Stop when body is in a straight line.", "default_sets": 3, "default_reps": "12-15", "default_rest": 60},
        {"id": 63, "name": "Cable Lateral Raise", "category": "Shoulders", "primary_muscles": ["Side Delts", "Shoulders"], "secondary_muscles": ["Traps"], "equipment": "Cable Machine", "difficulty": "Beginner", "environment": "Gym", "goal": "Hypertrophy", "instructions": "Attach single handle to lowest cable pulley. Stand sideways, pull handle across body out to shoulder height. Lower with resistance.", "start_pos": "Cable across body at hip.", "movement": "Raise arm laterally to 90 degrees.", "end_pos": "Arm at shoulder height.", "common_mistakes": "Leaning torso", "safety_notes": "Provides continuous tension unlike dumbbells.", "default_sets": 3, "default_reps": "12-15", "default_rest": 45},
        {"id": 64, "name": "Face Pull", "category": "Shoulders", "primary_muscles": ["Rear Delts", "Rotator Cuff", "Shoulders"], "secondary_muscles": ["Traps", "Rhomboids"], "equipment": "Cable Machine", "difficulty": "Beginner", "environment": "Gym", "goal": "General Fitness", "instructions": "Set rope attachment at eye level on cable machine. Pull rope ends towards eyes, separating hands and rotating forearms up. Hold 1 sec, extend arms smoothly.", "start_pos": "Standing holding rope with arms straight in front.", "movement": "Pull rope towards bridge of nose, externally rotating shoulders.", "end_pos": "Hands by ears with elbows high.", "common_mistakes": "Pulling too low", "safety_notes": "Essential for shoulder health and posture.", "default_sets": 3, "default_reps": "15", "default_rest": 60},
        {"id": 65, "name": "Dumbbell Front Raise", "category": "Shoulders", "primary_muscles": ["Front Delts", "Shoulders"], "secondary_muscles": ["Traps"], "equipment": "Dumbbells", "difficulty": "Beginner", "environment": "Home", "goal": "Hypertrophy", "instructions": "Hold dumbbells in front of thighs. Raise one or both arms forward to shoulder height. Lower under control.", "start_pos": "Standing holding dumbbells against thighs.", "movement": "Raise straight arm forward.", "end_pos": "Dumbbell at eye level.", "common_mistakes": "Rocking body", "safety_notes": "Control the descent.", "default_sets": 3, "default_reps": "12", "default_rest": 60},
        {"id": 66, "name": "Pike Push-Up", "category": "Shoulders", "primary_muscles": ["Shoulders", "Front Delts"], "secondary_muscles": ["Triceps", "Upper Chest", "Core"], "equipment": "Bodyweight", "difficulty": "Intermediate", "environment": "Home", "goal": "Strength", "instructions": "Get into downward dog position with hips high in an inverted V. Lower top of head towards floor between hands. Press back up through shoulders.", "start_pos": "Inverted V-shape with hands on floor and hips high.", "movement": "Lower head diagonally forward.", "end_pos": "Press back up to pike apex.", "common_mistakes": "Letting hips drop into regular pushup", "safety_notes": "Great bodyweight alternative to overhead press.", "default_sets": 3, "default_reps": "8-12", "default_rest": 60},
        {"id": 67, "name": "Upright Row", "category": "Shoulders", "primary_muscles": ["Side Delts", "Traps", "Shoulders"], "secondary_muscles": ["Biceps", "Forearms"], "equipment": "Barbell", "difficulty": "Intermediate", "environment": "Gym", "goal": "Hypertrophy", "instructions": "Grip bar with shoulder-width grip. Pull bar vertically up along torso, driving elbows high. Lower slowly.", "start_pos": "Standing holding barbell at thighs.", "movement": "Pull bar upwards leading with elbows.", "end_pos": "Bar at mid-chest, elbows high.", "common_mistakes": "Grip too narrow", "safety_notes": "Keep grip at shoulder width to protect rotator cuff.", "default_sets": 3, "default_reps": "10-12", "default_rest": 60},
        {"id": 68, "name": "Spider Curl", "category": "Biceps", "primary_muscles": ["Biceps"], "secondary_muscles": ["Brachialis"], "equipment": "Dumbbells", "difficulty": "Intermediate", "environment": "Gym", "goal": "Hypertrophy", "instructions": "Lie chest-down on an incline bench. Let arms hang straight down with dumbbells. Curl weights up without moving upper arms.", "start_pos": "Prone on incline bench, arms perpendicular to floor.", "movement": "Curl weights towards forehead.", "end_pos": "Full peak contraction.", "common_mistakes": "Swinging elbows back", "safety_notes": "Eliminates momentum completely.", "default_sets": 3, "default_reps": "12", "default_rest": 60},
        {"id": 69, "name": "Reverse Barbell Curl", "category": "Biceps", "primary_muscles": ["Brachialis", "Forearms", "Biceps"], "secondary_muscles": ["Brachioradialis"], "equipment": "Barbell", "difficulty": "Beginner", "environment": "Gym", "goal": "Muscle Gain", "instructions": "Grip barbell with overhand (pronated) grip. Curl bar up keeping wrists straight. Lower under control.", "start_pos": "Standing holding barbell with knuckles facing forward.", "movement": "Curl bar upwards with overhand grip.", "end_pos": "Bar at chest level.", "common_mistakes": "Wrist curling backward", "safety_notes": "Strengthens forearm extensors and upper arm thickness.", "default_sets": 3, "default_reps": "12-15", "default_rest": 60},
        {"id": 70, "name": "Diamond Push-Up", "category": "Triceps", "primary_muscles": ["Triceps", "Chest"], "secondary_muscles": ["Front Delts", "Core"], "equipment": "Bodyweight", "difficulty": "Intermediate", "environment": "Home", "goal": "Strength", "instructions": "Place hands close together on floor under chest forming a diamond with thumbs and index fingers. Lower chest to hands. Press back up.", "start_pos": "Plank with diamond hand position under sternum.", "movement": "Lower chest towards hands.", "end_pos": "Full press extension.", "common_mistakes": "Hips sagging", "safety_notes": "Excellent tricep bodyweight builder.", "default_sets": 3, "default_reps": "10-12", "default_rest": 60},
        {"id": 71, "name": "Dumbbell Tricep Kickback", "category": "Triceps", "primary_muscles": ["Triceps"], "secondary_muscles": ["Rear Delts"], "equipment": "Dumbbells", "difficulty": "Beginner", "environment": "Home", "goal": "Hypertrophy", "instructions": "Hinge forward at hips, upper arm parallel to torso. Extend forearm backward until arm is straight. Squeeze tricep, return to 90 deg.", "start_pos": "Bent over, elbow pinned at side at 90 degrees.", "movement": "Extend dumbbell backward.", "end_pos": "Arm fully straight behind torso.", "common_mistakes": "Dropping upper arm", "safety_notes": "Keep upper arm locked horizontally.", "default_sets": 3, "default_reps": "12-15", "default_rest": 45},
        {"id": 72, "name": "Cable Overhead Tricep Extension", "category": "Triceps", "primary_muscles": ["Triceps"], "secondary_muscles": ["Core"], "equipment": "Cable Machine", "difficulty": "Intermediate", "environment": "Gym", "goal": "Hypertrophy", "instructions": "Attach rope to high pulley, face away in lunge stance. Extend rope forward and overhead until arms lock out. Bend elbows back slowly.", "start_pos": "Lunge stance facing away from cable, rope behind head.", "movement": "Extend arms forward overhead.", "end_pos": "Arms locked out overhead, ropes spread.", "common_mistakes": "Losing balance", "safety_notes": "Brace core to keep posture steady.", "default_sets": 3, "default_reps": "12-15", "default_rest": 60},
        {"id": 73, "name": "Reverse Wrist Curls", "category": "Forearms", "primary_muscles": ["Forearms"], "secondary_muscles": ["Brachioradialis"], "equipment": "Dumbbells", "difficulty": "Beginner", "environment": "Home", "goal": "Hypertrophy", "instructions": "Rest forearms on bench with palms down. Extend wrists upward. Lower slowly.", "start_pos": "Forearms on bench, palms facing floor holding dumbbells.", "movement": "Extend wrists upwards.", "end_pos": "Top of wrist extension.", "common_mistakes": "Using too much weight", "safety_notes": "Use light weights for wrist health.", "default_sets": 3, "default_reps": "15", "default_rest": 45},
        {"id": 74, "name": "Dead Hang", "category": "Forearms", "primary_muscles": ["Forearms", "Grip"], "secondary_muscles": ["Lats", "Shoulders"], "equipment": "Pull-up Bar", "difficulty": "Beginner", "environment": "Gym", "goal": "Endurance", "instructions": "Grip pull-up bar with both hands. Hang freely with feet off floor, breathing deeply. Hold for max duration.", "start_pos": "Full hanging position from bar.", "movement": "Hold grip isometric contraction.", "end_pos": "Step down safely.", "common_mistakes": "Holding breath", "safety_notes": "Great for grip strength and spinal decompression.", "default_sets": 3, "default_reps": "45-60 sec", "default_rest": 60},
        {"id": 75, "name": "Hanging Leg Raise", "category": "Core", "primary_muscles": ["Abs", "Core"], "secondary_muscles": ["Hip Flexors", "Forearms"], "equipment": "Pull-up Bar", "difficulty": "Advanced", "environment": "Gym", "goal": "Strength", "instructions": "Hang from pull-up bar. Keeping legs straight, raise feet up to bar level. Lower under control without swinging.", "start_pos": "Dead hang from bar.", "movement": "Raise toes to bar level.", "end_pos": "Feet parallel or touching bar.", "common_mistakes": "Swinging body", "safety_notes": "Bend knees for an easier intermediate progression.", "default_sets": 3, "default_reps": "10-12", "default_rest": 60},
        {"id": 76, "name": "Bicycle Crunches", "category": "Core", "primary_muscles": ["Obliques", "Abs", "Core"], "secondary_muscles": ["Hip Flexors"], "equipment": "Bodyweight", "difficulty": "Beginner", "environment": "Home", "goal": "Hypertrophy", "instructions": "Lie on back with hands behind head, knees bent. Touch right elbow to left knee while extending right leg. Alternate sides smoothly.", "start_pos": "Supine, shoulders elevated, knees at 90 deg.", "movement": "Pedal legs while rotating torso across.", "end_pos": "Opposite elbow and knee meet.", "common_mistakes": "Pulling neck", "safety_notes": "Keep steady rhythmic tempo.", "default_sets": 3, "default_reps": "20 total", "default_rest": 45},
        {"id": 77, "name": "Cable Woodchopper", "category": "Core", "primary_muscles": ["Obliques", "Core"], "secondary_muscles": ["Shoulders", "Abs"], "equipment": "Cable Machine", "difficulty": "Intermediate", "environment": "Gym", "goal": "Muscle Gain", "instructions": "Set high pulley on cable. Stand sideways, grip handle with both hands. Pull diagonally down across body to opposite hip. Return smoothly.", "start_pos": "Standing sideways to high pulley, arms extended.", "movement": "Rotate torso and pull handle diagonally down.", "end_pos": "Handle at opposite knee/hip.", "common_mistakes": "Bending arms", "safety_notes": "Pivot back foot as you rotate.", "default_sets": 3, "default_reps": "12 each side", "default_rest": 60},
        {"id": 78, "name": "Mountain Climbers", "category": "Core", "primary_muscles": ["Core", "Abs"], "secondary_muscles": ["Shoulders", "Cardio"], "equipment": "Bodyweight", "difficulty": "Beginner", "environment": "Home", "goal": "Conditioning", "instructions": "Start in high plank position. Drive one knee into chest, then switch quickly in a running motion. Maintain flat back.", "start_pos": "High plank posture.", "movement": "Rapid alternating knee drives.", "end_pos": "Continuous steady rhythm.", "common_mistakes": "Bouncing hips in air", "safety_notes": "Keep shoulders stacked over wrists.", "default_sets": 3, "default_reps": "30 sec", "default_rest": 45},
        {"id": 79, "name": "Barbell Front Squat", "category": "Legs", "primary_muscles": ["Quadriceps", "Core", "Legs"], "secondary_muscles": ["Glutes", "Upper Back"], "equipment": "Barbell", "difficulty": "Advanced", "environment": "Gym", "goal": "Strength", "instructions": "Rest barbell on front delts in clean rack position with elbows high. Squat upright until hip crease passes knees. Drive up keeping elbows pointed forward.", "start_pos": "Bar racked on front shoulders, elbows held high.", "movement": "Descend with completely upright torso.", "end_pos": "Drive back up to lockout.", "common_mistakes": "Elbows dropping", "safety_notes": "Demands strong core and thoracic extension.", "default_sets": 4, "default_reps": "6-8", "default_rest": 120},
        {"id": 80, "name": "Hack Squat", "category": "Legs", "primary_muscles": ["Quadriceps", "Legs"], "secondary_muscles": ["Glutes"], "equipment": "Machines", "difficulty": "Intermediate", "environment": "Gym", "goal": "Hypertrophy", "instructions": "Position shoulders and back against hack squat sled. Lower sled until knees reach 90 degrees. Press back up through midfoot and heels.", "start_pos": "Shoulders against pads, feet on platform.", "movement": "Descend into deep machine squat.", "end_pos": "Press back up.", "common_mistakes": "Heels peeling off platform", "safety_notes": "Great isolated quad builder with back support.", "default_sets": 3, "default_reps": "8-10", "default_rest": 90},
        {"id": 81, "name": "Walking Lunges", "category": "Legs", "primary_muscles": ["Quadriceps", "Glutes", "Legs"], "secondary_muscles": ["Hamstrings", "Calves", "Core"], "equipment": "Dumbbells", "difficulty": "Intermediate", "environment": "Home", "goal": "Conditioning", "instructions": "Hold dumbbells at sides. Step forward into a lunge, lower back knee to ground. Push off back leg to step directly into next forward lunge.", "start_pos": "Standing tall holding dumbbells.", "movement": "Continuous walking forward lunges.", "end_pos": "Finish target distance.", "common_mistakes": "Short steps jamming front knee", "safety_notes": "Step in train tracks rather than a tightrope.", "default_sets": 3, "default_reps": "20 total steps", "default_rest": 60},
        {"id": 82, "name": "Dumbbell Romanian Deadlift", "category": "Hamstrings", "primary_muscles": ["Hamstrings", "Glutes", "Legs"], "secondary_muscles": ["Lower Back"], "equipment": "Dumbbells", "difficulty": "Beginner", "environment": "Home", "goal": "Muscle Gain", "instructions": "Hold dumbbells in front of thighs. Hinge at hips, pushing glutes back until you feel deep stretch in hamstrings. Return to standing.", "start_pos": "Standing holding dumbbells at thighs.", "movement": "Hip hinge down along shins.", "end_pos": "Hips back, dumbbells at mid-shin.", "common_mistakes": "Bending knees too much", "safety_notes": "Keep weights close to legs.", "default_sets": 3, "default_reps": "10-12", "default_rest": 60},
        {"id": 83, "name": "Glute Bridge", "category": "Glutes", "primary_muscles": ["Glutes"], "secondary_muscles": ["Hamstrings", "Core"], "equipment": "Bodyweight", "difficulty": "Beginner", "environment": "Home", "goal": "General Fitness", "instructions": "Lie on back with knees bent, feet flat on floor hip-width. Drive through heels to raise hips off floor until aligned with knees. Squeeze glutes at top.", "start_pos": "Supine with knees bent and feet flat.", "movement": "Bridge hips upward.", "end_pos": "Hips fully extended.", "common_mistakes": "Arching lower back excessively", "safety_notes": "Great warmup or glute hypertrophy exercise.", "default_sets": 3, "default_reps": "15-20", "default_rest": 45},
        {"id": 84, "name": "Cable Glute Kickback", "category": "Glutes", "primary_muscles": ["Glutes"], "secondary_muscles": ["Hamstrings"], "equipment": "Cable Machine", "difficulty": "Beginner", "environment": "Gym", "goal": "Hypertrophy", "instructions": "Attach ankle cuff to low cable. Kick leg directly backward and slightly out, squeezing glute at peak. Return with control.", "start_pos": "Facing machine with cuff around ankle.", "movement": "Extend leg backward against cable.", "end_pos": "Peak glute contraction.", "common_mistakes": "Swinging lower back", "safety_notes": "Keep torso stationary.", "default_sets": 3, "default_reps": "12-15 each leg", "default_rest": 45},
        {"id": 85, "name": "Seated Leg Curl", "category": "Hamstrings", "primary_muscles": ["Hamstrings", "Legs"], "secondary_muscles": ["Calves"], "equipment": "Machines", "difficulty": "Beginner", "environment": "Gym", "goal": "Hypertrophy", "instructions": "Sit in machine, secure thigh pad firmly above knees. Curl legs down and back underneath seat. Hold contraction 1 sec, return slowly.", "start_pos": "Seated with legs extended straight on roller pad.", "movement": "Curl heels underneath seat.", "end_pos": "Full knee flexion.", "common_mistakes": "Thigh pad too loose", "safety_notes": "Places hamstrings under loaded stretch.", "default_sets": 3, "default_reps": "10-12", "default_rest": 60},
        {"id": 86, "name": "Standing Barbell Calf Raise", "category": "Calves", "primary_muscles": ["Calves", "Gastrocnemius"], "secondary_muscles": ["Soleus"], "equipment": "Barbell", "difficulty": "Intermediate", "environment": "Gym", "goal": "Strength", "instructions": "Place barbell across upper back, stand with balls of feet on calf block. Lower heels into deep stretch. Drive up onto toes, squeeze calves.", "start_pos": "Bar on traps, balls of feet on block.", "movement": "Rise up onto toes.", "end_pos": "Peak calf contraction.", "common_mistakes": "Bending knees", "safety_notes": "Keep knees locked straight to target gastrocnemius.", "default_sets": 4, "default_reps": "12-15", "default_rest": 60},
        {"id": 87, "name": "Seated Calf Raise", "category": "Calves", "primary_muscles": ["Soleus", "Calves"], "secondary_muscles": ["Gastrocnemius"], "equipment": "Machines", "difficulty": "Beginner", "environment": "Gym", "goal": "Hypertrophy", "instructions": "Sit at machine with knees bent at 90 deg under pad. Lower heels into full stretch. Press up onto toes, hold 1 sec.", "start_pos": "Seated with pad over thighs, heels dropped.", "movement": "Raise heels against resistance.", "end_pos": "Peak soleus contraction.", "common_mistakes": "Bouncing weights", "safety_notes": "Directly targets the deeper soleus muscle.", "default_sets": 3, "default_reps": "15", "default_rest": 45},
        {"id": 88, "name": "Single-Leg Dumbbell Calf Raise", "category": "Calves", "primary_muscles": ["Calves"], "secondary_muscles": ["Soleus"], "equipment": "Dumbbells", "difficulty": "Beginner", "environment": "Home", "goal": "Hypertrophy", "instructions": "Hold dumbbell in one hand, balance on one foot on a step edge. Lower heel for deep stretch, press up onto big toe. Repeat and switch legs.", "start_pos": "Standing on single foot on step.", "movement": "Raise heel up on single leg.", "end_pos": "Full extension.", "common_mistakes": "Rolling ankle outward", "safety_notes": "Hold a wall lightly with other hand for balance.", "default_sets": 3, "default_reps": "12-15 each leg", "default_rest": 45},
        {"id": 89, "name": "Burpees", "category": "Full Body", "primary_muscles": ["Full Body", "Chest", "Quadriceps"], "secondary_muscles": ["Shoulders", "Core", "Cardio"], "equipment": "Bodyweight", "difficulty": "Intermediate", "environment": "Home", "goal": "Conditioning", "instructions": "From standing, drop into squat and kick feet back into pushup. Perform a pushup, jump feet back to hands, jump explosively with hands overhead.", "start_pos": "Standing tall.", "movement": "Drop to pushup, snap feet forward, jump up.", "end_pos": "Vertical jump overhead.", "common_mistakes": "Sagging spine in plank", "safety_notes": "Pace your breathing rhythm.", "default_sets": 3, "default_reps": "10-15", "default_rest": 60},
        {"id": 90, "name": "Kettlebell Swing", "category": "Full Body", "primary_muscles": ["Glutes", "Hamstrings", "Full Body"], "secondary_muscles": ["Core", "Shoulders", "Forearms"], "equipment": "Kettlebell", "difficulty": "Intermediate", "environment": "Gym", "goal": "Strength", "instructions": "Hinge back with kettlebell between thighs. Snap hips forward explosively to swing kettlebell to chest height. Guide bell back smoothly.", "start_pos": "Hinged stance holding kettlebell.", "movement": "Explosive hip extension swings bell forward.", "end_pos": "Bell at chest height, glutes squeezed.", "common_mistakes": "Squatting instead of hinging", "safety_notes": "Power comes exclusively from hips.", "default_sets": 4, "default_reps": "15-20", "default_rest": 60},
        {"id": 91, "name": "Dumbbell Thrusters", "category": "Full Body", "primary_muscles": ["Quadriceps", "Shoulders", "Full Body"], "secondary_muscles": ["Glutes", "Triceps", "Core"], "equipment": "Dumbbells", "difficulty": "Intermediate", "environment": "Home", "goal": "Conditioning", "instructions": "Hold dumbbells at shoulders in a front rack. Perform a full squat, then drive up explosively and press dumbbells overhead. Lower weights back to shoulders as you descend into next squat.", "start_pos": "Standing with dumbbells at shoulders.", "movement": "Squat down, then drive up into overhead press.", "end_pos": "Arms locked overhead in full standing extension.", "common_mistakes": "Pausing between squat and press", "safety_notes": "Seamless fluid momentum transfer from legs to shoulders.", "default_sets": 3, "default_reps": "10-12", "default_rest": 75},
        {"id": 92, "name": "Barbell Clean and Press", "category": "Full Body", "primary_muscles": ["Full Body", "Shoulders", "Traps", "Quadriceps"], "secondary_muscles": ["Glutes", "Triceps", "Core"], "equipment": "Barbell", "difficulty": "Advanced", "environment": "Gym", "goal": "Strength", "instructions": "Pull barbell from floor, explosively clean it onto front deltoids, then press bar overhead. Lower with control to floor.", "start_pos": "Barbell over midfoot in deadlift setup.", "movement": "Explosive triple extension into clean rack, then overhead press.", "end_pos": "Barbell locked overhead.", "common_mistakes": "Arm pulling instead of hip drive", "safety_notes": "Master clean technique with light weight first.", "default_sets": 4, "default_reps": "5", "default_rest": 120},
        {"id": 93, "name": "Box Jumps", "category": "Full Body", "primary_muscles": ["Quadriceps", "Glutes", "Calves"], "secondary_muscles": ["Hamstrings", "Cardio"], "equipment": "Bodyweight", "difficulty": "Intermediate", "environment": "Gym", "goal": "Conditioning", "instructions": "Stand in front of sturdy plyo box. Swing arms, hinge hips, and jump onto box landing softly in partial squat. Step down safely.", "start_pos": "Standing 1-2 feet in front of box.", "movement": "Explosive jump onto top of box.", "end_pos": "Soft landing on box, stand tall.", "common_mistakes": "Landing stiff-legged", "safety_notes": "Step down one foot at a time.", "default_sets": 3, "default_reps": "8-10", "default_rest": 60},
        {"id": 94, "name": "Battle Ropes", "category": "Full Body", "primary_muscles": ["Shoulders", "Core", "Full Body"], "secondary_muscles": ["Forearms", "Cardio"], "equipment": "Resistance Bands", "difficulty": "Beginner", "environment": "Gym", "goal": "Conditioning", "instructions": "Hold rope ends in half-squat athletic stance. Whip ropes up and down in alternating waves as fast as possible for target time.", "start_pos": "Athletic quarter squat, holding ropes.", "movement": "Alternating rhythmic wave slams.", "end_pos": "Complete interval duration.", "common_mistakes": "Standing upright", "safety_notes": "Maintain rooted stance throughout.", "default_sets": 4, "default_reps": "30 sec", "default_rest": 45},
        {"id": 95, "name": "Rowing Machine Intervals", "category": "Cardio", "primary_muscles": ["Back", "Legs", "Cardio"], "secondary_muscles": ["Biceps", "Core", "Forearms"], "equipment": "Machines", "difficulty": "Beginner", "environment": "Gym", "goal": "Endurance", "instructions": "Sit on rower, strap feet. Drive with legs, lean back slightly, pull handle to lower ribs. Extend arms, hinge forward, bend knees back to catch.", "start_pos": "Catch position: knees bent, arms straight forward.", "movement": "Leg drive -> hip hinge -> arm pull.", "end_pos": "Legs extended, handle at sternum.", "common_mistakes": "Pulling with arms before legs push", "safety_notes": "60% leg power, 20% core, 20% arm pull.", "default_sets": 4, "default_reps": "500m", "default_rest": 90},
        {"id": 96, "name": "Jump Rope", "category": "Cardio", "primary_muscles": ["Calves", "Cardio"], "secondary_muscles": ["Forearms", "Shoulders"], "equipment": "Bodyweight", "difficulty": "Beginner", "environment": "Home", "goal": "Endurance", "instructions": "Hold rope handles at hip height. Turn rope with wrists, jumping 1-2 inches off floor on balls of feet. Maintain light steady rhythm.", "start_pos": "Standing holding jump rope behind heels.", "movement": "Rhythmic jumping on balls of feet.", "end_pos": "Complete time interval.", "common_mistakes": "Jumping too high", "safety_notes": "Land softly with knees slightly bent.", "default_sets": 4, "default_reps": "60 sec", "default_rest": 30},
        {"id": 97, "name": "Dynamic Chest Stretch", "category": "Mobility", "primary_muscles": ["Chest", "Shoulders"], "secondary_muscles": ["Biceps"], "equipment": "No Equipment", "difficulty": "Beginner", "environment": "Home", "goal": "General Fitness", "instructions": "Stand tall with arms outstretched. Cross arms over chest in hug, then swing them wide open to stretch pectorals dynamically.", "start_pos": "Standing with arms open wide.", "movement": "Dynamic arm hugs and swings.", "end_pos": "Deep open chest stretch.", "common_mistakes": "Jerking violently", "safety_notes": "Perform before upper body workouts.", "default_sets": 2, "default_reps": "15 swings", "default_rest": 30},
        {"id": 98, "name": "Cat-Cow Stretch", "category": "Mobility", "primary_muscles": ["Back", "Core", "Mobility"], "secondary_muscles": ["Spine"], "equipment": "No Equipment", "difficulty": "Beginner", "environment": "Home", "goal": "General Fitness", "instructions": "On all fours, inhale and arch back down, looking up (Cow). Exhale, round spine up towards ceiling and tuck chin (Cat). Flow smoothly between postures.", "start_pos": "Quadruped on hands and knees.", "movement": "Spinal flexion and extension flow.", "end_pos": "Mobilized thoracic and lumbar spine.", "common_mistakes": "Rushing through without breathing", "safety_notes": "Excellent for spinal decompression.", "default_sets": 2, "default_reps": "10 cycles", "default_rest": 30},
        {"id": 99, "name": "Worlds Greatest Stretch", "category": "Mobility", "primary_muscles": ["Hip Flexors", "Hamstrings", "Thoracic Spine"], "secondary_muscles": ["Glutes", "Shoulders"], "equipment": "No Equipment", "difficulty": "Intermediate", "environment": "Home", "goal": "General Fitness", "instructions": "Step into long lunge with hands on floor inside front foot. Drop inside elbow towards floor, then rotate arm up towards ceiling opening chest. Repeat on both sides.", "start_pos": "Deep lunge with hands inside front foot.", "movement": "Elbow drops to instep, then rotates high to sky.", "end_pos": "Full thoracic rotation.", "common_mistakes": "Collapsing back knee", "safety_notes": "Unbeatable comprehensive pre-workout warmup.", "default_sets": 2, "default_reps": "6 each side", "default_rest": 30},
        {"id": 100, "name": "Hamstring Dynamic Sweep", "category": "Mobility", "primary_muscles": ["Hamstrings", "Mobility"], "secondary_muscles": ["Calves", "Lower Back"], "equipment": "No Equipment", "difficulty": "Beginner", "environment": "Home", "goal": "General Fitness", "instructions": "Step one heel forward with toes up. Hinge hips back, sweep hands down past foot in a smooth arc, and stand up. Alternate steps.", "start_pos": "Standing feet hip-width.", "movement": "Heel tap with sweeping arm hinge.", "end_pos": "Stand tall, step forward with other foot.", "common_mistakes": "Bending back instead of hinging hips", "safety_notes": "Warm up posterior chain prior to leg training.", "default_sets": 2, "default_reps": "10 each leg", "default_rest": 30},
        {"id": 101, "name": "Thoracic Spine Rotations", "category": "Mobility", "primary_muscles": ["Thoracic Spine", "Back", "Mobility"], "secondary_muscles": ["Shoulders"], "equipment": "No Equipment", "difficulty": "Beginner", "environment": "Home", "goal": "General Fitness", "instructions": "Kneel on all fours with one hand behind head. Rotate elbow down towards supporting arm, then flare elbow high towards ceiling. Switch sides.", "start_pos": "Quadruped with one hand behind ear.", "movement": "Rotate elbow from under torso high to ceiling.", "end_pos": "Full mid-back rotation.", "common_mistakes": "Shifting hips side to side", "safety_notes": "Improves posture and overhead pressing mobility.", "default_sets": 2, "default_reps": "10 each side", "default_rest": 30},
        {"id": 102, "name": "Svend Press", "category": "Chest", "primary_muscles": ["Chest"], "secondary_muscles": ["Front Delts"], "equipment": "Dumbbells", "difficulty": "Beginner", "environment": "Gym", "goal": "Hypertrophy", "instructions": "Squeeze weight plates or dumbbell between flat palms in front of chest. Press hands straight forward while maintaining maximal inward squeeze. Pull back to chest.", "start_pos": "Standing tall, pressing weight between palms at sternum.", "movement": "Extend arms forward horizontally under continuous inward pressure.", "end_pos": "Arms extended, chest contracted peak.", "common_mistakes": "Gripping edges instead of pressing flat palms", "safety_notes": "Constant isometric chest adduction.", "default_sets": 3, "default_reps": "12-15", "default_rest": 45},
        {"id": 103, "name": "Landmine Press", "category": "Shoulders", "primary_muscles": ["Front Delts", "Upper Chest", "Shoulders"], "secondary_muscles": ["Triceps", "Core"], "equipment": "Barbell", "difficulty": "Intermediate", "environment": "Gym", "goal": "Strength", "instructions": "Stand in staggered stance holding end of landmine barbell at shoulder. Press barbell diagonally upward until arm is straight. Lower back to shoulder under control.", "start_pos": "Staggered stance holding end of barbell at collarbone.", "movement": "Press diagonally upward along natural bar arc.", "end_pos": "Arm extended overhead forward.", "common_mistakes": "Arching back excessively", "safety_notes": "Extremely shoulder-friendly pressing angle.", "default_sets": 3, "default_reps": "10 each arm", "default_rest": 60},
        {"id": 104, "name": "Sissy Squat", "category": "Legs", "primary_muscles": ["Quadriceps", "Legs"], "secondary_muscles": ["Core", "Calves"], "equipment": "Bodyweight", "difficulty": "Advanced", "environment": "Home", "goal": "Hypertrophy", "instructions": "Stand holding a sturdy pole or wall for balance. Rise onto toes and lean torso back in a straight line while driving knees forward. Lower until knees are in deep flexion, drive quads to stand.", "start_pos": "Standing tall on toes, holding support.", "movement": "Torso leans back as knees push forward.", "end_pos": "Deep quad stretch, return to top.", "common_mistakes": "Bending at hips instead of knees", "safety_notes": "Intense direct quad overload.", "default_sets": 3, "default_reps": "8-10", "default_rest": 60},
        {"id": 105, "name": "Cable Rope Overhead Tricep Extension", "category": "Triceps", "primary_muscles": ["Triceps"], "secondary_muscles": ["Core"], "equipment": "Cable Machine", "difficulty": "Intermediate", "environment": "Gym", "goal": "Hypertrophy", "instructions": "Set low or mid cable with rope. Turn away, hold rope behind head, extend arms forward/upward. Spread rope apart at full extension.", "start_pos": "Staggered stance facing away, rope behind neck.", "movement": "Extend forearms forward.", "end_pos": "Arms straight overhead, rope ends apart.", "common_mistakes": "Elbows moving forward and back", "safety_notes": "Long head tricep builder with continuous tension.", "default_sets": 3, "default_reps": "12-15", "default_rest": 60},
        {"id": 106, "name": "Kettlebell Goblet Squat", "category": "Legs", "primary_muscles": ["Quadriceps", "Glutes", "Legs"], "secondary_muscles": ["Core"], "equipment": "Kettlebell", "difficulty": "Beginner", "environment": "Home", "goal": "General Fitness", "instructions": "Hold kettlebell by horns against chest. Squat deep, keeping chest tall. Drive up through feet.", "start_pos": "Standing holding kettlebell at chest.", "movement": "Squat down between legs.", "end_pos": "Stand back to vertical.", "common_mistakes": "Knees collapsing", "safety_notes": "Keep kettlebell in contact with sternum.", "default_sets": 3, "default_reps": "12", "default_rest": 60},
        {"id": 107, "name": "Barbell Glute Bridge", "category": "Glutes", "primary_muscles": ["Glutes"], "secondary_muscles": ["Hamstrings"], "equipment": "Barbell", "difficulty": "Intermediate", "environment": "Gym", "goal": "Hypertrophy", "instructions": "Lie on floor with knees bent and barbell across hips. Drive through heels to bridge hips upward. Squeeze glutes 2 sec at top, lower slowly.", "start_pos": "Supine with loaded bar on hips.", "movement": "Bridge pelvis upward.", "end_pos": "Peak glute contraction.", "common_mistakes": "Over-arching lower spine", "safety_notes": "Use bar pad for comfort.", "default_sets": 3, "default_reps": "10-12", "default_rest": 75},
        {"id": 108, "name": "Plate Pinch Hold", "category": "Forearms", "primary_muscles": ["Forearms", "Grip"], "secondary_muscles": ["Fingers"], "equipment": "Barbell", "difficulty": "Intermediate", "environment": "Gym", "goal": "Strength", "instructions": "Pinch two smooth weight plates together with fingers and thumb. Stand tall and hold for time without letting plates slip.", "start_pos": "Standing holding weight plates pinched in fingers.", "movement": "Hold static pinch grip.", "end_pos": "Set plates down safely.", "common_mistakes": "Resting plates against thighs", "safety_notes": "Increases thumb pinch strength and grip tenacity.", "default_sets": 3, "default_reps": "30 sec", "default_rest": 45},
        {"id": 109, "name": "Wall Sit", "category": "Legs", "primary_muscles": ["Quadriceps", "Legs"], "secondary_muscles": ["Glutes", "Calves"], "equipment": "Bodyweight", "difficulty": "Beginner", "environment": "Home", "goal": "Endurance", "instructions": "Lean back flat against wall, slide down until thighs are parallel to ground. Hold static 90-degree knee angle for target duration.", "start_pos": "Back against wall, knees bent at 90 degrees.", "movement": "Hold isometric wall sit.", "end_pos": "Push off wall to stand.", "common_mistakes": "Hands resting on knees", "safety_notes": "Keep knees stacked directly above ankles.", "default_sets": 3, "default_reps": "45-60 sec", "default_rest": 45},
        {"id": 110, "name": "Hollow Body Hold", "category": "Core", "primary_muscles": ["Abs", "Core"], "secondary_muscles": ["Hip Flexors"], "equipment": "Bodyweight", "difficulty": "Intermediate", "environment": "Home", "goal": "Endurance", "instructions": "Lie on back, press lower spine into floor. Raise arms overhead and legs 6 inches off floor, creating a shallow banana curve. Hold position.", "start_pos": "Supine with lower back sealed to ground.", "movement": "Elevate arms and legs into hollow shape.", "end_pos": "Hold hollow isometric contraction.", "common_mistakes": "Lower back lifting off floor", "safety_notes": "Foundation for gymnastic core stability.", "default_sets": 3, "default_reps": "30-45 sec", "default_rest": 45},
        {"id": 111, "name": "Kettlebell Sumo Deadlift", "category": "Legs", "primary_muscles": ["Glutes", "Hamstrings", "Legs"], "secondary_muscles": ["Adductors", "Lower Back"], "equipment": "Kettlebell", "difficulty": "Beginner", "environment": "Gym", "goal": "Strength", "instructions": "Stand with wide stance, toes flared 45 degrees. Hinge hips back and grip kettlebell handle with both hands. Drive through heels to stand.", "start_pos": "Wide sumo stance over kettlebell.", "movement": "Drive hips forward to stand tall.", "end_pos": "Standing erect with glutes contracted.", "common_mistakes": "Knees collapsing inward", "safety_notes": "Keep shins perpendicular to floor.", "default_sets": 3, "default_reps": "10-12", "default_rest": 60},
        {"id": 112, "name": "Single-Arm Cable Row", "category": "Back", "primary_muscles": ["Lats", "Back"], "secondary_muscles": ["Biceps", "Core"], "equipment": "Cable Machine", "difficulty": "Beginner", "environment": "Gym", "goal": "Hypertrophy", "instructions": "Grip single handle on cable machine in athletic stance. Pull elbow back past torso, rotating slightly for deep lat contraction.", "start_pos": "Standing facing cable with arm extended.", "movement": "Drive elbow back into hip.", "end_pos": "Handle at ribs with lat fully contracted.", "common_mistakes": "Excessive twisting", "safety_notes": "Isolates each lat individually.", "default_sets": 3, "default_reps": "10-12 each side", "default_rest": 45}
    ]

    for item in new_ex:
        slug = item["name"].lower().replace(" ", "_").replace("-", "_")
        inst = item["instructions"]
        inst_list = inst.split(". ") if isinstance(inst, str) else inst
        cm = item["common_mistakes"]
        cm_list = [cm] if isinstance(cm, str) else cm
        
        ex_map[item["id"]] = {
            "id": item["id"],
            "name": item["name"],
            "slug": slug,
            "category": item["category"],
            "primary_muscles": item["primary_muscles"],
            "secondary_muscles": item["secondary_muscles"],
            "equipment": item["equipment"],
            "difficulty": item["difficulty"],
            "environment": item["environment"],
            "goal": item["goal"],
            "instructions": inst_list,
            "start_pos": item["start_pos"],
            "movement": item["movement"],
            "end_pos": item["end_pos"],
            "common_mistakes": cm_list,
            "safety_notes": item["safety_notes"],
            "default_sets": item["default_sets"],
            "default_reps": item["default_reps"],
            "default_rest": item["default_rest"],
            "supported_demo": True,
            "media_type": "animation",
            "media_path": f"/static/exercises/{slug}/demo.svg",
            "demonstration_asset": f"/static/exercises/{slug}/demo.svg",
            "thumbnail": f"/static/exercises/{slug}/thumbnail.png",
            "aliases": [item["name"].lower()]
        }

    new_fd = [
        {"id": 23, "name": "Brown Rice", "category": "Grains", "serving_size_g": 100, "calories": 111, "protein": 2.6, "carbs": 23.0, "fat": 0.9, "fiber": 1.8, "cost_approx": 15, "common_unit": "1 cup cooked (150g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 24, "name": "Poha", "category": "Breakfast", "serving_size_g": 150, "calories": 220, "protein": 4.0, "carbs": 40.0, "fat": 5.0, "fiber": 2.5, "cost_approx": 15, "common_unit": "1 plate (150g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 25, "name": "Whole Wheat Bread", "category": "Grains", "serving_size_g": 60, "calories": 140, "protein": 6.0, "carbs": 24.0, "fat": 2.0, "fiber": 3.5, "cost_approx": 10, "common_unit": "2 slices (60g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 26, "name": "Besan Cheela", "category": "Breakfast", "serving_size_g": 100, "calories": 180, "protein": 9.0, "carbs": 22.0, "fat": 6.0, "fiber": 4.0, "cost_approx": 20, "common_unit": "2 cheelas (100g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 27, "name": "Khichdi (Rice & Moong Dal)", "category": "Grains", "serving_size_g": 200, "calories": 240, "protein": 8.0, "carbs": 42.0, "fat": 4.5, "fiber": 4.0, "cost_approx": 25, "common_unit": "1 bowl (200g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 28, "name": "Sweet Potato (Boiled)", "category": "Vegetables", "serving_size_g": 150, "calories": 130, "protein": 2.0, "carbs": 30.0, "fat": 0.2, "fiber": 4.0, "cost_approx": 15, "common_unit": "1 medium (150g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 29, "name": "Boiled Potato", "category": "Vegetables", "serving_size_g": 150, "calories": 130, "protein": 3.0, "carbs": 30.0, "fat": 0.2, "fiber": 3.0, "cost_approx": 10, "common_unit": "1 medium (150g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 30, "name": "Quinoa (Cooked)", "category": "Grains", "serving_size_g": 100, "calories": 120, "protein": 4.4, "carbs": 21.3, "fat": 1.9, "fiber": 2.8, "cost_approx": 35, "common_unit": "1 cup cooked (185g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 31, "name": "Cornflakes with Milk", "category": "Breakfast", "serving_size_g": 200, "calories": 210, "protein": 8.0, "carbs": 36.0, "fat": 3.5, "fiber": 1.5, "cost_approx": 25, "common_unit": "1 bowl (200ml)", "is_vegetarian": True, "is_vegan": False},
        {"id": 32, "name": "Plain Paratha", "category": "Grains", "serving_size_g": 70, "calories": 210, "protein": 4.5, "carbs": 28.0, "fat": 9.0, "fiber": 3.0, "cost_approx": 10, "common_unit": "1 paratha (70g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 33, "name": "Moong Dal (Cooked)", "category": "Legumes", "serving_size_g": 150, "calories": 130, "protein": 9.0, "carbs": 19.0, "fat": 1.5, "fiber": 5.0, "cost_approx": 15, "common_unit": "1 bowl (150g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 34, "name": "Masoor Dal (Red Lentils)", "category": "Legumes", "serving_size_g": 150, "calories": 140, "protein": 9.5, "carbs": 20.0, "fat": 2.0, "fiber": 5.5, "cost_approx": 15, "common_unit": "1 bowl (150g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 35, "name": "Black Eyed Peas (Lobia Curry)", "category": "Legumes", "serving_size_g": 150, "calories": 150, "protein": 8.0, "carbs": 23.0, "fat": 2.5, "fiber": 5.0, "cost_approx": 20, "common_unit": "1 bowl (150g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 36, "name": "Sprouted Moong Salad", "category": "Legumes", "serving_size_g": 100, "calories": 105, "protein": 8.0, "carbs": 18.0, "fat": 0.5, "fiber": 4.5, "cost_approx": 15, "common_unit": "1 bowl (100g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 37, "name": "Kala Chana (Boiled Black Chickpeas)", "category": "Legumes", "serving_size_g": 100, "calories": 164, "protein": 9.0, "carbs": 27.0, "fat": 2.5, "fiber": 7.5, "cost_approx": 15, "common_unit": "1 bowl (100g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 38, "name": "Egg Whites (Boiled)", "category": "Poultry/Eggs", "serving_size_g": 100, "calories": 52, "protein": 11.0, "carbs": 0.7, "fat": 0.2, "fiber": 0.0, "cost_approx": 18, "common_unit": "3 egg whites (100g)", "is_vegetarian": False, "is_vegan": False},
        {"id": 39, "name": "Egg Omelette (2 Eggs)", "category": "Poultry/Eggs", "serving_size_g": 120, "calories": 190, "protein": 13.0, "carbs": 2.0, "fat": 14.5, "fiber": 0.5, "cost_approx": 20, "common_unit": "2 egg omelette (120g)", "is_vegetarian": False, "is_vegan": False},
        {"id": 40, "name": "Toned Milk", "category": "Dairy", "serving_size_g": 200, "calories": 116, "protein": 6.2, "carbs": 9.4, "fat": 6.0, "fiber": 0.0, "cost_approx": 12, "common_unit": "1 glass (200ml)", "is_vegetarian": True, "is_vegan": False},
        {"id": 41, "name": "Greek Yogurt (Hung Curd)", "category": "Dairy", "serving_size_g": 100, "calories": 95, "protein": 10.0, "carbs": 3.8, "fat": 4.5, "fiber": 0.0, "cost_approx": 35, "common_unit": "1 cup (100g)", "is_vegetarian": True, "is_vegan": False},
        {"id": 42, "name": "Whey Protein Shake", "category": "Dairy", "serving_size_g": 30, "calories": 120, "protein": 24.0, "carbs": 2.0, "fat": 1.5, "fiber": 0.5, "cost_approx": 65, "common_unit": "1 scoop (30g)", "is_vegetarian": True, "is_vegan": False},
        {"id": 43, "name": "Buttermilk (Chaas)", "category": "Dairy", "serving_size_g": 200, "calories": 45, "protein": 3.0, "carbs": 4.5, "fat": 1.5, "fiber": 0.0, "cost_approx": 10, "common_unit": "1 glass (200ml)", "is_vegetarian": True, "is_vegan": False},
        {"id": 44, "name": "Chicken Curry (Home Style)", "category": "Meat", "serving_size_g": 150, "calories": 220, "protein": 24.0, "carbs": 5.0, "fat": 11.5, "fiber": 1.0, "cost_approx": 50, "common_unit": "1 bowl (150g)", "is_vegetarian": False, "is_vegan": False},
        {"id": 45, "name": "Grilled Chicken Thigh", "category": "Meat", "serving_size_g": 100, "calories": 209, "protein": 26.0, "carbs": 0.0, "fat": 10.9, "fiber": 0.0, "cost_approx": 40, "common_unit": "1 thigh (100g)", "is_vegetarian": False, "is_vegan": False},
        {"id": 46, "name": "Salmon / Rawas Fillet", "category": "Meat", "serving_size_g": 100, "calories": 208, "protein": 22.0, "carbs": 0.0, "fat": 13.0, "fiber": 0.0, "cost_approx": 110, "common_unit": "1 fillet (100g)", "is_vegetarian": False, "is_vegan": False},
        {"id": 47, "name": "Canned Tuna in Water", "category": "Meat", "serving_size_g": 100, "calories": 116, "protein": 26.0, "carbs": 0.0, "fat": 1.0, "fiber": 0.0, "cost_approx": 85, "common_unit": "1/2 can (100g)", "is_vegetarian": False, "is_vegan": False},
        {"id": 48, "name": "Prawns (Cooked)", "category": "Meat", "serving_size_g": 100, "calories": 99, "protein": 21.0, "carbs": 0.2, "fat": 1.1, "fiber": 0.0, "cost_approx": 90, "common_unit": "6-8 prawns (100g)", "is_vegetarian": False, "is_vegan": False},
        {"id": 49, "name": "Mutton / Lamb Curry", "category": "Meat", "serving_size_g": 150, "calories": 290, "protein": 23.0, "carbs": 4.0, "fat": 19.0, "fiber": 1.0, "cost_approx": 95, "common_unit": "1 bowl (150g)", "is_vegetarian": False, "is_vegan": False},
        {"id": 50, "name": "Almonds", "category": "Nuts/Seeds", "serving_size_g": 30, "calories": 175, "protein": 6.0, "carbs": 6.0, "fat": 15.0, "fiber": 3.5, "cost_approx": 25, "common_unit": "15-20 almonds (30g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 51, "name": "Walnuts", "category": "Nuts/Seeds", "serving_size_g": 30, "calories": 195, "protein": 4.5, "carbs": 4.0, "fat": 20.0, "fiber": 2.0, "cost_approx": 35, "common_unit": "7-8 halves (30g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 52, "name": "Peanut Butter", "category": "Snacks", "serving_size_g": 32, "calories": 190, "protein": 8.0, "carbs": 7.0, "fat": 16.0, "fiber": 2.0, "cost_approx": 20, "common_unit": "2 tbsp (32g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 53, "name": "Makhana (Fox Nuts)", "category": "Snacks", "serving_size_g": 30, "calories": 105, "protein": 3.0, "carbs": 23.0, "fat": 0.3, "fiber": 2.5, "cost_approx": 25, "common_unit": "1 bowl roasted (30g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 54, "name": "Chia Seeds", "category": "Nuts/Seeds", "serving_size_g": 15, "calories": 73, "protein": 2.5, "carbs": 6.3, "fat": 4.6, "fiber": 5.1, "cost_approx": 15, "common_unit": "1 tbsp (15g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 55, "name": "Flax Seeds", "category": "Nuts/Seeds", "serving_size_g": 15, "calories": 80, "protein": 2.7, "carbs": 4.3, "fat": 6.3, "fiber": 4.1, "cost_approx": 10, "common_unit": "1 tbsp ground (15g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 56, "name": "Pumpkin Seeds", "category": "Nuts/Seeds", "serving_size_g": 30, "calories": 170, "protein": 9.0, "carbs": 4.0, "fat": 14.0, "fiber": 2.0, "cost_approx": 30, "common_unit": "2 tbsp (30g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 57, "name": "Sattu Drink (Roasted Gram Flour)", "category": "Beverages", "serving_size_g": 40, "calories": 160, "protein": 10.0, "carbs": 26.0, "fat": 2.0, "fiber": 6.5, "cost_approx": 15, "common_unit": "1 glass (40g powder in water)", "is_vegetarian": True, "is_vegan": True},
        {"id": 58, "name": "Dates (Khajoor)", "category": "Fruits", "serving_size_g": 50, "calories": 140, "protein": 1.2, "carbs": 37.0, "fat": 0.2, "fiber": 4.0, "cost_approx": 20, "common_unit": "4-5 dates (50g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 59, "name": "Papaya", "category": "Fruits", "serving_size_g": 150, "calories": 65, "protein": 0.8, "carbs": 16.0, "fat": 0.4, "fiber": 2.6, "cost_approx": 15, "common_unit": "1 bowl cubed (150g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 60, "name": "Guava", "category": "Fruits", "serving_size_g": 100, "calories": 68, "protein": 2.6, "carbs": 14.0, "fat": 1.0, "fiber": 5.4, "cost_approx": 10, "common_unit": "1 medium (100g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 61, "name": "Orange", "category": "Fruits", "serving_size_g": 130, "calories": 62, "protein": 1.2, "carbs": 15.0, "fat": 0.2, "fiber": 3.1, "cost_approx": 15, "common_unit": "1 medium (130g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 62, "name": "Watermelon", "category": "Fruits", "serving_size_g": 200, "calories": 60, "protein": 1.2, "carbs": 15.0, "fat": 0.3, "fiber": 0.8, "cost_approx": 15, "common_unit": "1 large slice (200g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 63, "name": "Pomegranate", "category": "Fruits", "serving_size_g": 100, "calories": 83, "protein": 1.7, "carbs": 19.0, "fat": 1.2, "fiber": 4.0, "cost_approx": 35, "common_unit": "1/2 cup arils (100g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 64, "name": "Mango", "category": "Fruits", "serving_size_g": 150, "calories": 90, "protein": 1.2, "carbs": 22.0, "fat": 0.6, "fiber": 2.4, "cost_approx": 30, "common_unit": "1 cup cubed (150g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 65, "name": "Spinach (Palak Sabzi)", "category": "Vegetables", "serving_size_g": 150, "calories": 75, "protein": 4.0, "carbs": 6.0, "fat": 3.5, "fiber": 3.5, "cost_approx": 20, "common_unit": "1 bowl (150g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 66, "name": "Broccoli (Steamed)", "category": "Vegetables", "serving_size_g": 100, "calories": 35, "protein": 2.8, "carbs": 7.0, "fat": 0.4, "fiber": 2.6, "cost_approx": 30, "common_unit": "1 cup (100g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 67, "name": "Cucumber (Salad)", "category": "Vegetables", "serving_size_g": 100, "calories": 15, "protein": 0.7, "carbs": 3.6, "fat": 0.1, "fiber": 0.5, "cost_approx": 8, "common_unit": "1 medium cucumber (100g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 68, "name": "Tomatoes", "category": "Vegetables", "serving_size_g": 100, "calories": 18, "protein": 0.9, "carbs": 3.9, "fat": 0.2, "fiber": 1.2, "cost_approx": 6, "common_unit": "1 medium tomato (100g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 69, "name": "Bhindi (Okra Masala)", "category": "Vegetables", "serving_size_g": 150, "calories": 120, "protein": 3.0, "carbs": 12.0, "fat": 6.5, "fiber": 4.5, "cost_approx": 25, "common_unit": "1 bowl (150g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 70, "name": "Cauliflower (Gobi Curry)", "category": "Vegetables", "serving_size_g": 150, "calories": 110, "protein": 3.5, "carbs": 11.0, "fat": 5.5, "fiber": 3.5, "cost_approx": 20, "common_unit": "1 bowl (150g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 71, "name": "Green Peas (Matar)", "category": "Vegetables", "serving_size_g": 100, "calories": 81, "protein": 5.4, "carbs": 14.5, "fat": 0.4, "fiber": 5.7, "cost_approx": 15, "common_unit": "1/2 cup (100g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 72, "name": "Button Mushrooms", "category": "Vegetables", "serving_size_g": 100, "calories": 22, "protein": 3.1, "carbs": 3.3, "fat": 0.3, "fiber": 1.0, "cost_approx": 35, "common_unit": "1 cup sliced (100g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 73, "name": "Capsicum / Bell Pepper", "category": "Vegetables", "serving_size_g": 100, "calories": 26, "protein": 1.0, "carbs": 6.0, "fat": 0.3, "fiber": 2.1, "cost_approx": 15, "common_unit": "1 medium pepper (100g)", "is_vegetarian": True, "is_vegan": True},
        {"id": 74, "name": "Ghee", "category": "Dairy", "serving_size_g": 10, "calories": 90, "protein": 0.0, "carbs": 0.0, "fat": 10.0, "fiber": 0.0, "cost_approx": 8, "common_unit": "1 tsp (5g) or 2 tsp (10g)", "is_vegetarian": True, "is_vegan": False},
        {"id": 75, "name": "Green Tea", "category": "Beverages", "serving_size_g": 200, "calories": 2, "protein": 0.2, "carbs": 0.0, "fat": 0.0, "fiber": 0.0, "cost_approx": 5, "common_unit": "1 cup (200ml)", "is_vegetarian": True, "is_vegan": True},
        {"id": 76, "name": "Black Coffee", "category": "Beverages", "serving_size_g": 200, "calories": 2, "protein": 0.3, "carbs": 0.0, "fat": 0.0, "fiber": 0.0, "cost_approx": 5, "common_unit": "1 mug (200ml)", "is_vegetarian": True, "is_vegan": True},
        {"id": 77, "name": "Coconut Water", "category": "Beverages", "serving_size_g": 250, "calories": 45, "protein": 1.7, "carbs": 8.9, "fat": 0.5, "fiber": 2.6, "cost_approx": 40, "common_unit": "1 fresh coconut (250ml)", "is_vegetarian": True, "is_vegan": True}
    ]

    for item in new_fd:
        fd_map[item["id"]] = item

    sorted_ex = [ex_map[k] for k in sorted(ex_map.keys())]
    sorted_fd = [fd_map[k] for k in sorted(fd_map.keys())]

    with open(ex_file, "w", encoding="utf-8") as f:
        json.dump(sorted_ex, f, indent=2)

    with open(fd_file, "w", encoding="utf-8") as f:
        json.dump(sorted_fd, f, indent=2)

    print(f"Successfully expanded exercises.json to {len(sorted_ex)} items and foods.json to {len(sorted_fd)} items.")

if __name__ == "__main__":
    build()

